# Generated by Django 5.0.1 on 2024-02-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('standard', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('total_subjects', models.PositiveIntegerField()),
                ('subject1_mark', models.PositiveIntegerField()),
                ('subject2_mark', models.PositiveIntegerField()),
                ('subject3_mark', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('percentage', models.FloatField()),
                ('pass_fail_status', models.CharField(max_length=10)),
            ],
        ),
    ]
