# Generated by Django 5.0.1 on 2024-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0002_rename_subject1_mark_student_english_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(blank=True, choices=[('cs', 'Computer Science'), ('bio', 'Bio-Math')], max_length=20, null=True),
        ),
    ]
