# Generated by Django 5.0.1 on 2024-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0005_middlestudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSecondaryBioMathStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('standard', models.CharField(max_length=10)),
                ('number_of_subjects', models.PositiveIntegerField()),
                ('tamil_mark', models.PositiveIntegerField()),
                ('english_mark', models.PositiveIntegerField()),
                ('maths_mark', models.PositiveIntegerField()),
                ('physics_mark', models.PositiveIntegerField()),
                ('chemistry_mark', models.PositiveIntegerField()),
                ('biology_mark', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('percentage', models.FloatField()),
                ('pass_fail_status', models.CharField(max_length=10)),
                ('tamil_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('english_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('maths_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('physics_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('chemistry_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('biology_grade', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
