# Generated by Django 4.2.3 on 2024-02-02 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managementsystem', '0007_highstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('test_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HighSecondaryComputerScienceStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('standard', models.CharField(max_length=10)),
                ('number_of_subjects', models.PositiveIntegerField()),
                ('tamil_mark', models.PositiveIntegerField()),
                ('english_mark', models.PositiveIntegerField()),
                ('maths_mark', models.PositiveIntegerField()),
                ('physics_mark', models.PositiveIntegerField()),
                ('chemistry_mark', models.PositiveIntegerField()),
                ('computer_science_mark', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('percentage', models.FloatField()),
                ('pass_fail_status', models.CharField(max_length=10)),
                ('tamil_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('english_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('maths_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('physics_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('chemistry_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('computer_science_grade', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField()),
                ('grades', models.JSONField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementsystem.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
