# Generated by Django 4.0.8 on 2024-02-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0008_assignment_highsecondarycomputersciencestudent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('test_link', models.URLField()),
                ('questions', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='testsubmission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='testsubmission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='TestSubmission',
        ),
    ]
